"""Alert and Category models

Revision ID: 31f979bca494
Revises: 71d25aaef758
Create Date: 2025-05-15 23:45:56.249168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31f979bca494"
down_revision: Union[str, None] = "71d25aaef758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "alerts",
        sa.Column("comment", sa.String(length=255), nullable=True),
        sa.Column("room_number", sa.Integer(), nullable=True),
        sa.Column("category_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["category_name"],
            ["categories.name"],
            name=op.f("fk_alerts_category_name_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["room_number"], ["rooms.number"], name=op.f("fk_alerts_room_number_rooms")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alerts")
    op.drop_table("categories")
    # ### end Alembic commands ###
