"""Admin, Token, Update Room

Revision ID: 49af6d7703d5
Revises: 51d0219c7214
Create Date: 2025-05-18 03:53:20.744424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49af6d7703d5'
down_revision: Union[str, None] = '51d0219c7214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('username', name=op.f('uq_admins_username'))
    )
    op.create_table('tokens',
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_tokens_token'))
    )
    op.add_column('rooms', sa.Column('plate_token', sa.String(length=256), nullable=True))
    op.add_column('rooms', sa.Column('mac_address', sa.String(length=256), nullable=True))
    op.create_unique_constraint(op.f('uq_rooms_mac_address'), 'rooms', ['mac_address'])
    op.create_unique_constraint(op.f('uq_rooms_plate_token'), 'rooms', ['plate_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rooms_plate_token'), 'rooms', type_='unique')
    op.drop_constraint(op.f('uq_rooms_mac_address'), 'rooms', type_='unique')
    op.drop_column('rooms', 'mac_address')
    op.drop_column('rooms', 'plate_token')
    op.drop_table('tokens')
    op.drop_table('admins')
    # ### end Alembic commands ###
