"""Bookings and Rooms

Revision ID: 6370aa6ee82e
Revises: 
Create Date: 2025-05-15 19:24:31.007940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6370aa6ee82e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=50), nullable=False),
    sa.Column('passport', sa.String(length=10), nullable=False),
    sa.Column('peoples', sa.Integer(), nullable=False),
    sa.Column('date_in', sa.Date(), nullable=False),
    sa.Column('date_out', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['room_number'], ['rooms.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('rooms')
    # ### end Alembic commands ###
