"""Update room

Revision ID: d41adfeb923f
Revises: 31f979bca494
Create Date: 2025-05-16 19:02:34.177111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d41adfeb923f"
down_revision: Union[str, None] = "31f979bca494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms", sa.Column("level", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "level")
    # ### end Alembic commands ###
