"""Create Customer

Revision ID: 60af35b25bbd
Revises: d41adfeb923f
Create Date: 2025-05-17 11:16:09.385390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60af35b25bbd"
down_revision: Union[str, None] = "d41adfeb923f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("passport", sa.String(length=256), nullable=False),
        sa.Column(
            "booking_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_customers_booking_id_bookings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.drop_column("bookings", "customer")
    op.drop_column("bookings", "passport")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "passport", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "customer", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_table("customers")
    # ### end Alembic commands ###
